name: Deploy Build Folder
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install && npm run build
      - run: git add -f build
      - run: git commit -m "Auto-deploy build folder" || echo "No changes to commit"
      - run: git push origin main
